version: '3.8'

services:
  docsite:
    build:
      context: .
      network: host
    container_name: docsite
    restart: unless-stopped
    ports:
      - "3120:3000"
    volumes:
      - ./data/config:/app/config
      - ./data/docs:/app/docs
      - ./data/uploads:/app/docs/uploads
      - ./public:/app/public
