version: '3.8'

services:
  docsite:
    image: kaushik678/docsite:latest
    container_name: docsite
    restart: unless-stopped
    ports:
      - "3100:3000"
    volumes:
      - ./data/config:/app/config
      - ./data/docs:/app/docs
      - ./data/uploads:/app/docs/uploads
